language: node_js
dist: trusty

node_js:
  - 'node'

services:
  - docker

install:
  - npm install
  - npm install start-server-and-test
  - missdev --https

script:
  - npm run ci:cypress:angular

sudo: required
