language: node_js
dist: trusty

node_js:
  - 'node'

services:
  - docker

install:
  - npm install
  - npm install start-server-and-test

script:
  - npm run ci:cypress:run:guillotina;

sudo: required
